"""change tables

Revision ID: 8bc0b880de98
Revises: 50a8ce6a7020
Create Date: 2023-06-05 19:47:05.245438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc0b880de98'
down_revision = '50a8ce6a7020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_cakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.drop_column('_price')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.drop_column('_total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_total_price', sa.NUMERIC(precision=8, scale=2), nullable=True))
        batch_op.drop_column('total_price')

    with op.batch_alter_table('order_cakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_price', sa.NUMERIC(precision=8, scale=2), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
